# Generated by Django 5.2.1 on 2025-05-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa'),
            preserve_default=False,
        ),
    ]
